### ISSUE TITLE
7. 实现聊天完成评价界面  Assigned to kakazuo

### ISSUE THREAD

**Issue by yiyie1** [yiyie1/TalknicApp#8]

**Comment by kakazuo** [comment]
1. 创建一个新的表来记录comments以及score
2. 计算一个人的综合评分

**Comment by yiyie1** [comment]
AR：kakazuo
`1. 现有评分数据记录在talknic_user中的praise字段中；` 这条有误，现有的praise字段不表示评分功能，仅表示对他人点赞数；
2. 需完成新表设计以同时记录来自学员的评分，及评论（双向，包括学员及教师），可参考talknic_order的设计及代码参考case 16 & 17；
3. 更新评分数据以供显示评分到home主界面中；
4. 评分数据应是平均值；

**Comment by yiyie1** [comment]
1. 聊天完成界面已基本完成；
2. 数据库添加talknic_rate来记录评价及评论；
3. case 35，36用来读取记录相关数据；
4. case 17也已更新用来在付款发生时，记录order_id到talknic_rate中；
5. TODO: 原本计划是想在talknic_order直接增加字段来记录评价数据，但是不知为何无法更新新添加字段的数据，所以workaround是添加新表talknic_rate，以后可以将这两张表合并；

**Comment by kakazuo** [comment]
@yiyie1 你这个功能已经完成了是吧

**Comment by yiyie1** [comment]
功能基本完成，后面有完善的需要将另开一个任务。@kakazuo
